const USER_LOGGED_IN = "USER_LOGGED_IN";
const USER_LOGGED_OUT = "USER_LOGGED_OUT";
const USER_SIGNED_UP = "USER_SIGNED_UP";
const GET_ERRORS = "GET_ERRORS";
const GET_ALL_PROFILES = "GET_ALL_PROFILES";
const PROFILES_LOADING = "PROFILES_LOADING";
const GET_PROFILE = "GET_PROFILE";
const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
const CLEAR_ERROR = "CLEAR_ERROR";
const CREATE_PROFILE = "CREATE_PROFILE";
const DELETE_USER_ACCOUNT = "DELETE_USER_ACCOUNT";
const ADD_EXPERIENCE = "ADD_EXPERIENCE";
const ADD_EDUCATION = "ADD_EDUCATION";
const REMOVE_FROM_PROFILE =  "REMOVE_FROM_PROFILE";
const GET_BY_HANDLE = "GET_BY_HANDLE";
const CREATE_POST = "CREATE_POST";
const GET_POSTS = "GET_POSTS";
const POSTS_LOADING = "POSTS_LOADING";
const LIKE_POST = "LIKE_POST";

export {
  USER_LOGGED_IN, USER_LOGGED_OUT, USER_SIGNED_UP,
  GET_ERRORS, GET_ALL_PROFILES, PROFILES_LOADING,
  GET_PROFILE, CLEAR_CURRENT_PROFILE, CLEAR_ERROR,
  CREATE_PROFILE, DELETE_USER_ACCOUNT, ADD_EXPERIENCE,
  ADD_EDUCATION, REMOVE_FROM_PROFILE, GET_BY_HANDLE,
  CREATE_POST, GET_POSTS, POSTS_LOADING, LIKE_POST
}
